Repository AY2324S2-CS2103T-F11-2/tp, pull requests merged in 2024-03, with the labels that each got.

#33 update DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#32 update AboutUs
  docs/AboutUs.md
  docs/images/darkarche3.png
  docs/team/Darkarche3.md
Labels: type.Documentation

#38 Update README.md
  README.md
Labels: type.Documentation

#39 Update README.md
  README.md
Labels: type.Documentation

#40 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#50 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#49 Add Borrow.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/BorrowCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Borrow.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Epic, priority.High

#61 Branch fixing checkstyle
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/BorrowCommandParser.java
  src/main/java/seedu/address/model/person/Borrow.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug

#69 Fix bug in Borrow logic
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
Labels: type.Bug

#73 Create Book class
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/DonateCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/person/BookList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Epic

#76 Create valid book title
  src/main/java/seedu/address/model/book/Book.java
Labels: type.Enhancement

#78 Create and fix some test cases
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.Medium

#80 Branch borrow empty book
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#82 Fix Merit Score equality check
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/MeritScore.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
Labels: type.Bug

#85 Fix PersonTest
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, priority.Low

#93 Bug fixing for test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High

#100 Add images for Version Release
  build.gradle
  docs/images/borrow.png
  docs/images/donate.png
  docs/images/return.png
Labels: priority.High

#107 Create BorrowSequenceDiagram.puml
  docs/diagrams/BorrowSequenceDiagram.puml
Labels: type.Documentation

#106 update ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation, priority.High

#108 Update BorrowSequenceDiagram.puml
  docs/diagrams/BorrowSequenceDiagram.puml
Labels: type.Documentation

#118 Add BorrowCommandParserTest
  README.md
  src/test/java/seedu/address/logic/parser/BorrowCommandParserTest.java
Labels: type.Task, priority.High

#128 Change book list class implementation
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/DonateCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/BorrowCommandParser.java
  src/main/java/seedu/address/logic/parser/DonateCommandParser.java
  src/main/java/seedu/address/model/BookCollection.java
  src/main/java/seedu/address/model/person/BookList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#143 Fix borrow command to show new book
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug

#145 Add library logic
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.High

#146 Create limit command
  library.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LimitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LimitCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyLibrary.java
  src/main/java/seedu/address/model/library/Library.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/model/library/Threshold.java
  src/main/java/seedu/address/model/person/MeritScore.java
Labels: type.Enhancement, type.Story, priority.Medium

#147 Update Return Command and Library Logic
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/LimitCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyLibrary.java
  src/main/java/seedu/address/model/library/Library.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
Labels: type.Bug, priority.High

#148 Branch add library functions in model
  library.txt
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/library/Library.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/model/library/Threshold.java
Labels: type.Enhancement, priority.High

#151 Fix threshold save bug
  src/main/java/seedu/address/model/library/Library.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/model/library/Threshold.java
Labels: type.Bug, priority.High

#153 Update Ui to show library books
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/ui/LibraryCard.java
  src/main/java/seedu/address/ui/LibraryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LibraryListCard.fxml
  src/main/resources/view/LibraryListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#155 Change Version Number
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.Low

#157 Enabled Assertions
  build.gradle
Labels: type.Task, priority.High

#158 Update DG with Limit and Threshold implementation
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low

#160 Add ObservableList
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ReadOnlyLibrary.java
  src/main/java/seedu/address/model/library/Library.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#163 Enable auto update for books
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/main/java/seedu/address/logic/commands/DonateCommand.java
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyLibrary.java
  src/main/java/seedu/address/model/library/LibraryLogic.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug, priority.High
