Repository AY2324S2-CS2103T-F11-2/tp, pull requests merged in 2024-04, with the labels that each got.

#166 Update UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#169 Update Return User Guide
  docs/UserGuide.md
  docs/images/ReturnBookUserguide.png
Labels: type.Documentation, priority.Medium

#164 Add empty limit command
  src/main/java/seedu/address/logic/commands/LimitCommand.java
  src/main/java/seedu/address/logic/parser/LimitCommandParser.java
Labels: type.Enhancement, priority.Medium

#170 Update LibraryListCard to allow for text wrap
  src/main/resources/view/LibraryListCard.fxml
Labels: type.Enhancement, priority.Medium

#171 Improve UI
  src/main/java/seedu/address/ui/LibraryCard.java
  src/main/java/seedu/address/ui/LibraryListPanel.java
Labels: type.Task, priority.Medium

#173 Fix Ui Index issue
  src/main/java/seedu/address/ui/LibraryCard.java
Labels: type.Bug, priority.Medium

#175 Update UG with limit
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#174 Branch add book
  src/main/java/seedu/address/logic/commands/AddBookCommand.java
  src/main/java/seedu/address/logic/parser/AddBookCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddBookCommandTest.java
Labels: type.Epic, priority.High

#178 Add DeleteBookCommand
  src/main/java/seedu/address/logic/commands/DeleteBookCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteBookCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteBookCommandTest.java
Labels: type.Story, priority.Medium

#185 BorrowCommand Test
  src/main/java/seedu/address/logic/commands/BorrowCommand.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
Labels: priority.High

#186 Enhance Merit Score UI
  src/main/java/seedu/address/model/library/Threshold.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#187 Update User guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#190 Fix checkstyle
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
Labels: type.Bug, priority.High

#179 Incorporate Markbind into documentation
  .github/workflows/docs.yml
  .gitignore
  docs/.gitignore
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Gemfile
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_data/projects.yml
  docs/_includes/custom-head.html
  docs/_includes/head.html
  docs/_includes/header.html
  docs/_layouts/alt-page.html
  docs/_layouts/default.html
  docs/_layouts/page.html
  docs/_markbind/layouts/default.md
  docs/_markbind/variables.json
  docs/_markbind/variables.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/_sass/minima/custom-mixins.scss
  docs/_sass/minima/custom-styles.scss
  docs/_sass/minima/custom-variables.scss
  docs/_sass/minima/initialize.scss
  docs/_sass/minima/skins/classic.scss
  docs/_sass/minima/skins/solarized-dark.scss
  docs/_sass/minima/skins/solarized.scss
  docs/assets/css/style.scss
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/LogicStorageDIP.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/tracing/LogicSequenceDiagram.png
  docs/index.md
  docs/package-lock.json
  docs/package.json
  docs/site.json
  docs/stylesheets/main.css
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: type.Documentation, priority.Low

#194 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#196 Fix testcase for v1.3
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
  src/test/java/seedu/address/logic/commands/DonateCommandTest.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#198 Update Ui.png
  docs/images/Ui.png
Labels: type.Documentation, priority.Medium

#200 Update User Guide
  docs/UserGuide.md
  docs/images/AddBookUserguide.png
  docs/images/BorrowBookUserguide.png
  docs/images/DeleteBookUserGuide.png
  docs/images/ReturnBookUserguide.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Documentation, priority.High

#203 Change website logo
  docs/images/mybookshelflogo.png
  docs/site.json
Labels: type.Enhancement, priority.Low

#204 Update index.md
  docs/index.md
Labels: type.Task, priority.Low

#268 Fix some user guide bugs
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, priority.Low

#269 Update Future Enhancements in DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation, type.Enhancement, priority.Medium

#270 Enhance UserGuide to account for PE-D bugs
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, type.Enhancement, priority.Medium

#273 update UG
  docs/UserGuide.md
  docs/images/findJaneTanResult.png
Labels: type.Documentation, priority.High

#272 Add UC1 - Add borrower in the DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#277 Add UC2, UC3, UC4 to DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#276 Update Project Porfolio Page
  docs/team/Ty-stan0417.md
Labels: type.Documentation

#275 Update Project Portfolio page
  docs/team/Darkarche3.md
Labels: type.Documentation, priority.Low

#278 Add tests related to threshold
  src/main/java/seedu/address/logic/commands/LimitCommand.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/LimitCommandTest.java
  src/test/java/seedu/address/logic/parser/LimitCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/library/ThresholdTest.java
  src/test/java/seedu/address/model/person/MeritScoreStub.java
  src/test/java/seedu/address/testutil/TypicalThresholds.java
Labels: type.Task, priority.Medium

#285 Refactor library storage
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#286 Update User Guide
  docs/UserGuide.md
  docs/images/cmdimages/addbook Tales of Kokoro.png
  docs/images/cmdimages/addbook result Tales of Kokoro.png
  docs/images/cmdimages/borrow Tales of Kokoro.png
  docs/images/cmdimages/delbook Tales of Kokoro.png
  docs/images/cmdimages/delbook result Tales of Kokoro.png
  docs/images/cmdimages/donate Tales of Kokoro.png
  docs/images/cmdimages/limit num result.png
  docs/images/cmdimages/limit result.png
  docs/images/cmdimages/return Tales of Kokoro.png
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
Labels: type.Bug, type.Documentation, priority.High

#290 Branch update UG images
  docs/UserGuide.md
  docs/images/cmdimages/addKokoro.png
  docs/images/cmdimages/addbookTalesofKokoro.png
  docs/images/cmdimages/addbookresultTalesofKokoro.png
  docs/images/cmdimages/addresultKokoro.png
  docs/images/cmdimages/borrowTalesofKokoro.png
  docs/images/cmdimages/delbookTalesofKokoro.png
  docs/images/cmdimages/delbookresultTalesofKokoro.png
  docs/images/cmdimages/delete.png
  docs/images/cmdimages/deletebefore.png
  docs/images/cmdimages/deleteresult.png
  docs/images/cmdimages/donateTalesofKokoro.png
  docs/images/cmdimages/editMashiro.png
  docs/images/cmdimages/editbeforeMashiro.png
  docs/images/cmdimages/editresultMashiro.png
  docs/images/cmdimages/find.png
  docs/images/cmdimages/findresult.png
  docs/images/cmdimages/limitnumresult.png
  docs/images/cmdimages/limitresult.png
  docs/images/cmdimages/list.png
  docs/images/cmdimages/listresult.png
  docs/images/cmdimages/returnTalesofKokoro.png
Labels: type.Bug, type.Documentation, priority.High

#288 Update DG, add all relevant use cases.
  docs/DeveloperGuide.md
Labels: type.Documentation

#289 Change Librarian to Library manager, change user to library user in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#294 Fix all JsonAdaptedTest
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.TestCases

#296 Fix DeleteBookCommand tests
  src/main/java/seedu/address/logic/commands/DeleteBookCommand.java
  src/test/java/seedu/address/logic/commands/DeleteBookCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteBookCommandParserTest.java
Labels: type.TestCases

#293 Update DonateCommandTest to increase code test coverage
  src/test/java/seedu/address/logic/commands/DonateCommandTest.java
Labels: type.TestCases

#297 update User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#287 Fixes Prefix b/ bug
  src/main/java/seedu/address/logic/parser/AddBookCommandParser.java
  src/main/java/seedu/address/logic/parser/BorrowCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteBookCommandParser.java
  src/main/java/seedu/address/logic/parser/DonateCommandParser.java
  src/main/java/seedu/address/logic/parser/ReturnCommandParser.java
Labels: type.Bug, priority.High

#298 Standardized test case
  src/test/java/seedu/address/logic/commands/AddBookCommandTest.java
  src/test/java/seedu/address/logic/commands/BorrowCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteBookCommandTest.java
  src/test/java/seedu/address/logic/commands/DonateCommandTest.java
  src/test/java/seedu/address/logic/commands/ReturnCommandTest.java
Labels: type.TestCases

#300 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, priority.Medium

#299 Update glossary in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#301 Add Walkthrough Section to UG
  docs/UserGuide.md
  docs/images/cmdimages/Contact_List_Annotated.png
  docs/images/cmdimages/UG_UI_image.jpg
  docs/images/cmdimages/Ui_Annotated.png
Labels: type.Documentation, priority.High

#302 update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/Ty-stan0417.md
Labels: type.Documentation, priority.High

#306 Changes to Command and Model Class Diagram
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
Labels: type.Documentation, priority.Medium

#305 Add more test cases to increase coverage
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/LibraryStorage.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/MeritScoreTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/LibraryStorageTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.TestCases

#310 update Puml
  docs/diagrams/BorrowSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: type.Task

#313 Fix Images in Tutorial
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#316 update BorrowSequenceDiagram
  docs/diagrams/BorrowSequenceDiagram.puml
Labels: type.Documentation, priority.High

#311 Add LibraryModelClassDiagram
  docs/diagrams/LibraryModelClassDiagram.puml
  src/main/java/seedu/address/model/library/Library.java
Labels: type.Documentation, priority.High

#317 Add Quick Start for MacOS and Windows
  docs/UserGuide.md
  docs/images/QuickStart/MacOS/default.png
  docs/images/QuickStart/MacOS/jarmybookshelf.png
  docs/images/QuickStart/MacOS/search.png
  docs/images/QuickStart/MacOS/terminal.png
  docs/images/QuickStart/Windows/CommandPrompt.png
  docs/images/QuickStart/Windows/WindowsRtypeCMD.png
  docs/images/QuickStart/Windows/default.png
  docs/images/QuickStart/Windows/jarmybookshelf.png
Labels: type.Documentation

#321 Update Manual Test Case for DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#319 update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#320 Fix the UI so that the name, merit score and book is shown correctly
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.High

#326 update LogicManagerTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, type.TestCases

#329 Fix grammar
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low

#336 Add intro
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#338 update UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#342 Update intro
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#344 Remove use case links
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#345 Fix mistakes
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#346 update PPP
  docs/team/Darkarche3.md
Labels: type.Documentation
